Update error and add custom error handler for grpc-gateway
aserto-dev/go-utils pull request #11
Opened 2021-11-04 13:07 UTC by carabasdaniel

2021-11-05 17:52 UTC, stefanba3 submitted a review, later dismissed
LGTM!

2021-11-08 10:33 UTC, viovanov requested changes

2021-11-08 10:33 UTC, viovanov commented on grpcutil/custom_error_handler.go
> +				value, ok := t.Metadata["aserto-http-statuscode"]
can you please make this a constant?

2021-11-08 10:46 UTC, viovanov approved these changes

2021-11-08 10:46 UTC, merged